name: mangacampus_repo
description: A full build system for MangaCampus extension repositories.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  http: ^1.1.0
  html: ^0.15.4
  crypto: ^3.0.3

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
